import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <header>
          <nav>
            <img />
            <a href="/">Home</a>
            <a href="/events">Events</a>
            <a href="/blog">Blog</a>
            <a href="/about-us">About Us</a>
            <a href="/contact">Contact</a>
          </nav>
      </header>

      <main>

      </main>

      <footer>
      <p>&copy; 2023 ammocodes development</p>

      </footer>
      
    </>
  )
}
